# Generated by Django 2.2.4 on 2019-08-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('timeline', models.CharField(max_length=500)),
                ('ratio', models.CharField(max_length=500)),
                ('total_ratio', models.CharField(max_length=500)),
            ],
        ),
    ]
